# version: "3.8"

# services:
#   mange_ta_main:
#     build:
#       context: ./backend
#       target: dev
#     image: mange_ta_main:dev
#     ports:
#       - "8000:8000"
#     volumes:
#       - .:/app
#       - /app/.venv
#     networks:
#       - app_network
#     environment:
#       - UV_HOST=0.0.0.0
#       - UV_PORT=8000
#       - UV_RELOAD=True
    

#   mange_ta_main_front:
#     build:
#       context: ./frontend
#       target: dev
#     image: mange_ta_main_front:dev
#     ports:
#       - "8501:8501"
#     volumes:
#       - .:/app
#       - /app/.venv
#     networks:
#       - app_network
#     environment:
#       - BASE_URL=http://mange_ta_main:8000/mange_ta_main
   

# networks:
#   app_network:
#     driver: bridge

version: "3.8"

services:
  mange_ta_main:
    build:
      context: ./backend
      target: dev
    image: mange_ta_main:dev
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/.venv
    networks:
      - app_network
    environment:
      - UV_HOST=0.0.0.0
      - UV_PORT=8000
      - UV_RELOAD=True

  mange_ta_main_front:
    build:
      context: ./frontend
      target: dev
    image: mange_ta_main_front:dev
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
      - /app/.venv
    networks:
      - app_network
    depends_on:
      - mange_ta_main
    environment:
      - BACKEND_URL=http://mange_ta_main:8000
   
networks:
  app_network:
    driver: bridge